language: node_js
node_js:
  - lts/*
services: 
  - mongodb
script:
  - echo '*****Starting build*****'
  - cd url-service
  - echo 'Installing dependencies'
  - npm install
  - echo 'Running tests'
  - npm run test