name: Deploy to Google App Engine
on:
  push:
    branches:
      - master
jobs:
  build:
    name: GAE Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: generate_dotenv_file
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          NODE_ENV: ${{ secrets.NODE_ENV }}
        run: echo "$DB_USER" > ./url-service/app.yaml & echo "$DB_PASSWORD" > ./url-service/app.yaml & echo "$NODE_ENV" > ./url-service/app.yaml
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.gcp_credentials }}'
      - name: Google App Engine
        uses: 'google-github-actions/deploy-appengine@v0'
        with:
          project_id: url-shortener-362611
          version: master
          flags: --no-cache
          deliverables: ./url-service/app.yaml