name: Deploy to Google App Engine
on:
  push:
    branches:
      - master
jobs:
  build:
    name: GAE Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '$${{ secrets.gcp_credentials }}'
      - name: Google App Engine
        uses: google-github-actions/deploy-appengine@master
        with:
          project_id: url-shortener-362611
          version: master
          flags: --no-cache
          deliverables: app.yaml