name: Deploy to Google App Engine
on:
  push:
    branches:
      - master
jobs:
  build:
    name: GAE Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: generate_dotenv_file
        env:
          MY_DOTENV: '${{ secrets.MY_DOTENV }}'
        run: echo "$MY_DOTENV" > ./url-service/env.yaml

      - id: prepare-app-yaml
        uses: mshick/fast-envsubst@v1
        with:
          env-file: ./url-service/env.yaml
          in-file: ./url-service/app.yaml.template
          out-file: ./url-service/app.yaml

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.gcp_credentials }}'
      - name: Google App Engine
        uses: 'google-github-actions/deploy-appengine@v0'
        with:
          project_id: url-shortener-362611
          version: master
          flags: --no-cache
          deliverables: ./url-service/app.yaml